---
title: "modelo1"
author: "calopez"
date: "19/11/2021"
output: html_document
---
```{r setup, include=FALSE}
library(rstan)
library(readxl)
library(tidyverse)

options(mc.cores=parallel::detectCores());
#knitr::opts_chunk$set
devtools::install_github("lmoffatt/EvidenceCalcUsingRstan")
library(EvidenceCalcUsingRstan)

(echo = TRUE)
```

#importar datos
```{r}
df <- read_excel("modelo.xlsx")

```


# calcular el numero de serpientes vistas por mes
```{r}
df%>%group_by(Año,Mes)%>%summarise(nSerp=n())->df0



```




## modelo cero

```{stan output.var=model}

data {
   real<lower=0, upper=1> beta; // for Evidence
   int<lower=0> N; // number of measures
   // int<lower=0> K; // number of species 
     
   // here I declare the data we use in the model
   //int  iSpecies[N];
   //int  iAmbiente[N];
   
   real<lower=0> sampledAreaMonthly;
   

   
   int nSerpent[N];
   
     // here I declare some parameters that I have to come up with to describe the 
   // prior distribution of the fitted parameters. 
   // I provide a mean and a standard deviation for each one of the parameters 
   real  fp_mean_mean_log_site_density_prior;
   real <lower=0> fp_sd_mean_log_site_density_prior;
   
   
  }


parameters {
   // I had to do a little trick here, for some reason rstan works better if 
   // we work with standarized parameters (that after we substract the mean and divide by
   // the standard deviation). So the algorithm will work on this parameters: 
   // the real ones are the transformed ones

   real sn_mean_log_site_density_prior;
   
}

transformed parameters {
   // ... declarations ... statements ...
   // here I transform the standarize parameters to the regular ones.
   
   
   
   real mean_log_site_density=sn_mean_log_site_density_prior*
   fp_sd_mean_log_site_density_prior+fp_mean_mean_log_site_density_prior;
   

   
   real geometric_mean_site_density=exp(mean_log_site_density);

   
   
   real monthly_expected_sights=geometric_mean_site_density*sampledAreaMonthly;
   

}

model {
    // in this block we set the distributions.
    // I also hacked rstan to calculate the Evidence. 
    
    // I define two variables: prior and loglikelihood
   
   real prior;
   real loglikelihood;
   
   // in the prior I sum the prior distribution of the  working parameters, all normal
   // distributions of the transformed parameters
   prior=normal_lpdf(sn_mean_log_site_density_prior|0,1);
 
   
    // the likelihood function asses how good is the estimation of the expected number of sights per month
   loglikelihood=poisson_lpmf(nSerpent|monthly_expected_sights);


   // this is the distribution that is sampled: it depends on the parameter beta
   // we have to run this model for different values of beta from 0 to 1
   
   target+=prior+beta*loglikelihood;
   // ... declarations ... statements ...
}

generated quantities {
   // unfortunately I have to calculate again the prior and loglikelihood so rstan records its
   // values. 
   real prior; 
   real loglikelihood; 
   prior=normal_lpdf(sn_mean_log_site_density_prior|0,1);
     // the likelihood function asses how good is the estimation of the expected number of sights per transect
 loglikelihood=poisson_lpmf(nSerpent|monthly_expected_sights);



}

```


Now we build a function to feed stan with the data
```{r}
model_parameters<-c("geometric_mean_site_density");
```


```{r}
data_to_stan<-function(db, sampledArea){
   rdata<-list(beta=1,
   N=nrow(db),
   sampledAreaMonthly=sampledArea,
   
   nSerpent=db$nSerp,
   
fp_mean_mean_log_site_density_prior=1, # km^-2
   fp_sd_mean_log_site_density_prior=log(4)
                );
}
```



```{r}
sampledA = 36*8/1000*4+3.7*2*3/1000*26  # 36 km RN101 8 m ancho 4 veces por mes, 3.7 km macuco 3m ancho 26 veces al mes
rdata<-data_to_stan(df0,sampledArea=sampledA );


beta= c(0,0.01,0.03,0.1,0.3,1.0);
knitr::opts_chunk$set(echo = FALSE);
```


```{r}
r<-EvidenceCalcUsingRstan::runSampling(model=model,mydata=rdata,betavector = beta, betalabel="beta",iter=4000, thin=1);

```

Lets first calculate the evidence.

```{r}
knitr::opts_chunk$set(echo = TRUE);
E<-Evidencerun(r,beta);
E
```


The evidence is then 
```{r}
E$I$Ev 
```






Lets see the values for the parameters

```{r}
summary(r[[length(beta)]])->s;
s$summary->ss;
ss
```


Lets process the runs to plot them

```{r}
as.data.frame(r[[length(beta)]])->mcmc_1;
mcmc_1$beta=1;
as.data.frame(r[[1]])->mcmc_0;
mcmc_0$beta=0;

rbind(mcmc_0,mcmc_1)->mcmc2;
mcmc2$distribution=c("prior","posterior")[mcmc2$beta+1];


mcmc2%>%select(distribution,model_parameters)%>%pivot_longer(
    cols=model_parameters,
    names_to = "parameters", 
    values_to = "value",
    values_drop_na = TRUE
  )->parameters;





```

Lets see the plot of the parameters

```{r}
ggplot(parameters,aes(x=value, after_stat(ndensity),group=distribution))+geom_density(aes(fill=distribution),alpha=0.2)+
   facet_wrap(vars(parameters),ncol=2,scales ="free")+scale_x_log10()+
   theme(axis.title.y=element_blank(),
         axis.text.y=element_blank(),
         axis.ticks.y=element_blank()
         )
```
